<?php
/*=========================================================================================================================================================
 *
 *  PROJETO OSC MAGENTO BRASIL - VERSÃO FINAL V3.0
 *  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 *  O módulo One Step Checkout normatizado para a localização brasileira.
 *  site do projeto: http://onestepcheckout.com.br/
 *  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 *
 *
 *
 *  Mmantenedores do Projeto:
 *  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 *
 *  Deivison Arthur Lemos Serpa
 *  deivison.arthur@gmail.com
 *  www.deivison.com.br
 *  (21)9203-8986
 *
 *  Denis Colli Spalenza
 *  http://www.xpdev.com.br
 *
 *  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 *
 *
 *
 *  GOSTOU DO MÓDULO?
 *  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 *  Se você gostou, se foi útil para você, se fez você economizar aquela grana pois estava prestes a pagar caro por aquele módulo pago, pois não achava uma
 *  solução gratuita que te atendesse e queira prestigiar o trabalho feito efetuando uma doação de qualquer valor, não vou negar e vou ficar grato! você
 *  pode fazer isso visitando a página do projeto em: http://onestepcheckout.com.br/
 *  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 *
/*=========================================================================================================================================================
 */

$logged		= $this->isCustomerLoggedIn();
$has_addr	= $this->customerHasAddresses();

//echo Mage::getStoreConfig('design/head/default_charset');

?>      


<?php $this->setShowAddressFields(true);?>

<div class="onepagecheckout_block">
    <div class="op_block_title">
		<?php	echo $this->__('Name & Address');	?>
    </div>
    <div class="form_fields">
    <?php if ($has_addr){ ?>
        <div class="full">
            <label for="billing_cutomer_address">
            	<?php echo $this->__('Select a billing address from your address book or enter a new address.') ?>
            </label>
            <div class="data_area">
                <?php echo $this->getCustomerBillAddr() ?>
            </div>
        </div>
    <?php } ?>
	    <div id="bill_form"<?php if ($has_addr) {echo ' style="display:none;" ';} ?>>
			<input type="hidden" name="billing[address_id]" id="billing:address_id" value="<?php echo $this->getBillAddress()->getId() ?>" />

            <?php if (!$logged)  : ?>
            <?php endif; ?>

                                                                                                                <!-- getBillAddress -->
			<div class="two_fields">
				<?php echo $this->getLayout()->createBlock('onepagecheckout/widget_name')->setObject($this->getCustomer())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
			</div>
			<div class='clr'></div>



				<div class="full">
					<label for="billing:email" class="required">
						<?php echo $this->__('Email Address') ?>
					</label>
					<sup>*</sup>
					<div class="data_area">
						<input type="text" name="billing[email]" value="<?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="t1 validate-email required-entry" />
					</div>
				</div>



            <!--empresa-->
            <?php
			$company = Mage::getStoreConfig('onepagecheckout/address_form/company');
			if ($company !== 'hidden') : ?>
                <!-- company-->
				<div class="full">
                    <label for="company" <?php if ( $company  === 'required' ){ echo 'class="required"'; }?> ><?php echo $this->__('Empresa') ?></label>
					<?php if($company === 'required') { echo ' <sup>*</sup> ';}?>
					<div class="data_area">
						<input type="text" id="company" name="billing[company]" value="<?php echo $this->htmlEscape($this->getCustomer()->getEmpresa()) ?>" title="<?php echo $this->__('Empresa') ?>" class="input-text t1<?php if($company === 'required'){ echo ' required-entry';} ?>" />
					</div>
				</div>
            <?php endif; ?>


            <!--tipopessoa-->
            <?php
			$tipopessoa = Mage::getStoreConfig('onepagecheckout/address_form/tipopessoa');
			if ($tipopessoa !== 'hidden') : ?>
                <!-- tipopessoa-->
				<div class="full">
            	 	<?php $attribute = Mage::getModel('eav/config')->getAttribute('customer','tipopessoa'); ?>
                    <label for="tipopessoa" <?php if ( $tipopessoa  === 'required' ){ echo 'class="required"'; }?> ><?php echo $this->__('Tipo Pessoa') ?></label>
					<?php if($tipopessoa === 'required') { echo ' <sup>*</sup> ';}?>
					<div class="data_area">
                        <select name="billing[tipopessoa]" id="tipopessoa" class="input-text t1<?php if($tipopessoa === 'required'){ echo ' required-entry';} ?>" >

                        	<?php
                            if (version_compare(Mage::getVersion(), '1.7.0.2', '>=')){
                                 $options = $attribute->getSource()->getAllOptions();
                        		 foreach($options as $option){
                        	?>
                        		<option value='<?php echo $option['value']?>'><?php echo $this->__($option['label'])?></option>
                        	<?php };
                            }else{ ?>
                                 <option value=''>Escolha a opcao</option>
                                 <option value='1'>Fisica</option>
                                 <option value='2'>Juridica</option>
                                 <option value='3'>Outros</option>
                            <?php
                            }
                            ?>
                        </select>
                        <script type="text/javascript">
						//<![CDATA[
                            $j('#tipopessoa').children('option').eq(<?php echo $this->htmlEscape($this->getCustomer()->getTipopessoa()) ?>).attr('selected', 'selected');
						//]]>
						</script>
					</div>
				</div>
            <?php endif; ?>


            <!--rg-->
            <?php
			$rg = Mage::getStoreConfig('onepagecheckout/address_form/rg');
			if ($rg !== 'hidden') : ?>
                <!-- rg-->
				<div class="full">
                    <label for="rg" <?php if ( $rg  === 'required' ){ echo 'class="required"'; }?> ><?php echo $this->__('Identidade (RG)') ?></label>
					<?php if($rg === 'required') { echo ' <sup>*</sup> ';}?>
					<div class="data_area">
						<input type="text" id="rg" name="billing[rg]" value="<?php echo $this->htmlEscape($this->getCustomer()->getRg()) ?>" title="<?php echo $this->__('Identidade (RG)') ?>" class="input-text t1<?php if($rg === 'required'){ echo ' required-entry';} ?>" />
					</div>
				</div>
            <?php endif; ?>


            <!--ie-->
            <?php
			$ie = Mage::getStoreConfig('onepagecheckout/address_form/ie');
			if ($ie !== 'hidden') : ?>
                <!-- IE-->
				<div class="full">
                    <label for="ie" <?php if ( $ie  === 'required' ){ echo 'class="required"'; }?> ><?php echo $this->__('IE (Inscricao Estadual)') ?></label>
					<?php if($ie === 'required') { echo ' <sup>*</sup> ';}?>
					<div class="data_area">
						<input type="text" id="ie" name="billing[ie]" value="<?php echo $this->htmlEscape($this->getCustomer()->getIe()) ?>" title="<?php echo $this->__('IE (Inscricao Estadual)') ?>" class="input-text t1<?php if($ie === 'required'){ echo ' required-entry';} ?>" />
					</div>
				</div>
            <?php endif; ?>


            <!--cpf-->
            <?php
			$cpfcnpj = Mage::getStoreConfig('onepagecheckout/address_form/cpfcnpj');
			if ($cpfcnpj !== 'hidden') : ?>
                <!-- CNPJ e CPF billing:taxvat-->
				<div class="full">
                    <label for="billing:taxvat" <?php if ( $cpfcnpj  === 'required' ){ echo 'class="required"'; }?> >
						<?php echo $this->__('Taxvat') ?>
					</label>
					<?php if($cpfcnpj === 'required') { echo ' <sup>*</sup> ';}?>
					<div class="data_area">
						<input type="text" id="billing:taxvat" name="billing[cpfcnpj]" value="<?php echo $this->htmlEscape($this->getCustomer()->getCpfcnpj()) ?>" title="<?php echo $this->__('Taxvat') ?>" class="validar_cpf t1<?php if($cpfcnpj === 'required'){ echo ' required-entry';} ?>" />
					</div>
				</div>
            <?php endif; ?>

            <!--cpf Taxvat-->
            <?php
			$cpfcnpjtaxvat = Mage::getStoreConfig('onepagecheckout/address_form/cpfcnpjtaxvat');
			if ($cpfcnpjtaxvat !== 'hidden') : ?>
                <!-- CNPJ e CPF billing:taxvat-->
				<div class="full">
                    <label for="billing:taxvat" <?php if ( $cpfcnpjtaxvat  === 'required' ){ echo 'class="required"'; }?> >
						<?php echo $this->__('Taxvat') ?>
					</label>
					<?php if($cpfcnpjtaxvat === 'required') { echo ' <sup>*</sup> ';}?>
					<div class="data_area">
						<input type="text" id="billing:taxvat" name="billing[taxvat]" value="<?php echo $this->htmlEscape($this->getCustomer()->getCpfcnpj()) ?>" title="<?php echo $this->__('Taxvat') ?>" class="validar_cpf t1<?php if($cpfcnpjtaxvat === 'required'){ echo ' required-entry';} ?>" />
					</div>
				</div>
            <?php endif; ?>





			<?php
			$phone_r= Mage::getStoreConfig('onepagecheckout/address_form/phone');
			$fax_r	= Mage::getStoreConfig('onepagecheckout/address_form/fax');
			$celular	= Mage::getStoreConfig('onepagecheckout/address_form/celular');
			?>

            <?php if ($phone_r !== 'hidden' || $fax_r !== 'hidden' ) : ?>
            <div class="two_fields">

        				<?php if ($phone_r !== 'hidden') : ?>
        					<div class="short">
        						<label for="billing:telephone"<?php if($phone_r === 'required') { echo ' class="required" ';}?>>
        							<?php echo $this->__('Telephone') ?>
        						</label>
        						<?php if($phone_r === 'required') { echo ' <sup>*</sup> ';}?>
        						<div class="data_area">
        							<input type="text" name="billing[telephone]" value="<?php echo $this->htmlEscape($this->getBillAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="t1<?php if($phone_r === 'required') { echo ' required-entry ';}?>" id="billing:telephone" />
        						</div>
        					</div>
        				<?php endif; ?>

            			<?php if ($fax_r !== 'hidden') : ?>
            				<div class="short">
            					<label for="billing:fax"<?php if($fax_r === 'required') {echo ' class="required" ';}?>>
            						<?php echo $this->__('Fax') ?>
            					</label>
            					<?php if($fax_r === 'required') {echo ' <sup>*</sup> ';}?>
            					<div class="data_area">
            						<input type="text" name="billing[fax]" value="<?php echo $this->htmlEscape($this->getBillAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="t1<?php if($fax_r === 'required') {echo ' required-entry ';}?>" id="billing:fax" />
            					</div>
            				</div>
                        <?php endif ?>

            			<?php if ($celular !== 'hidden') : ?>
            				<div class="short">
            					<label for="billing:fax"<?php if($celular === 'required') {echo ' class="required" ';}?>>
            						<?php echo $this->__('Celular') ?>
            					</label>
            					<?php if($celular === 'required') {echo ' <sup>*</sup> ';}?>
            					<div class="data_area">
            						<input type="text" id="celular" name="billing[celular]" value="<?php echo $this->htmlEscape($this->getCustomer()->getCelular()) ?>" title="<?php echo $this->__('Celular') ?>" class="t1<?php if($celular === 'required') {echo ' required-entry ';}?>" id="billing:fax" />
            					</div>
            				</div>
                        <?php endif ?>

            </div>
            <div class='clr'></div>
            <?php endif ?>




            <div class="clr"></div>

			<?php
			$tracoAtivo = Mage::getStoreConfig('onepagecheckout/general/tracoativo');

			$zip_r	= Mage::getStoreConfig('onepagecheckout/address_form/zip');
			if ($zip_r !== 'hidden') :
			?>
					<div class="full">
						<label for="billing:postcode"<?php if($zip_r === 'required'){echo ' class="required" ';}?>>
							<?php echo $this->__('Zip Code') ?>
						</label>
						<?php if($zip_r === 'required'){echo ' <sup>* (somente n&uacute;meros)</sup>';}?>
						<div class="data_area">
							<input maxlength="8" type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->htmlEscape($this->getBillAddress()->getPostcode()) ?>" class="t1 validate-zip-international<?php if($zip_r === 'required'){echo ' required-entry ';}?> <?php if($tracoAtivo === '1'){ echo ' tracoAtivo';} ?>   " onblur="buscarEndereco('<?=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN)?>','billing');"/>
						</div>
					</div>
			<?php endif; ?>

            <div class="clr"></div>






            <!--enderecao-->
            <?php
			$endereco = Mage::getStoreConfig('onepagecheckout/address_form/address');
			if ($endereco !== 'hidden') : ?>
                <!-- endereco-->
				<div class="full">
                    <label for="endereco" <?php if ( $endereco  === 'required' ){ echo 'class="required"'; }?> ><?php echo $this->__('Endere&ccedil;o') ?></label>
					<?php if($endereco === 'required') { echo ' <sup>*</sup> ';}?>
					<div class="data_area">
						<input type="text" id="billing:street1" name="billing[street][1]" value="<?php echo $this->htmlEscape($this->getBillAddress()->getStreet(1)) ?>" title="<?php echo $this->__('Endere&ccedil;o') ?>" class="input-text t1<?php if($endereco === 'required'){ echo ' required-entry';} ?>" />
					</div>
				</div>
            <?php endif; ?>
            <!--Numero e Complemento-->
			<?php
			$complemento = Mage::getStoreConfig('onepagecheckout/address_form/address3');
            $numero = Mage::getStoreConfig('onepagecheckout/address_form/address2');
			?>

            <?php if ($numero !== 'hidden' || $complemento !== 'hidden' ) : ?>
            <div class="two_fields">

        				<?php if ($numero !== 'hidden') : ?>
        					<div class="short">
        						<label for="billing:street2"<?php if($numero === 'required') { echo ' class="required" ';}?>>
        							<?php echo $this->__('N&uacute;mero') ?>
        						</label>
        						<?php if($numero === 'required') { echo ' <sup>*</sup> ';}?>
        						<div class="data_area">
            						<input type="text" id="billing:street2" name="billing[street][2]" value="<?php echo $this->htmlEscape($this->getBillAddress()->getStreet(2)) ?>" title="<?php echo $this->__('N&uacute;mero') ?>" class="input-text t1<?php if($numero === 'required'){ echo ' required-entry';} ?>" />
        						</div>
        					</div>
        				<?php endif; ?>

            			<?php if ($complemento !== 'hidden') : ?>
            				<div class="short">
            					<label for="billing:street3"<?php if($complemento === 'required') {echo ' class="required" ';}?>>
            						<?php echo $this->__('Complemento') ?>
            					</label>
            					<?php if($complemento === 'required') {echo ' <sup>*</sup> ';}?>
            					<div class="data_area">
            						<input type="text" id="billing:street3" name="billing[street][3]" value="<?php echo $this->htmlEscape($this->getBillAddress()->getStreet(3)) ?>" title="<?php echo $this->__('Complemento') ?>" class="input-text t1<?php if($complemento === 'required'){ echo ' required-entry';} ?>" />
            					</div>
            				</div>
                        <?php endif ?>
            </div>
            <div class='clr'></div>
            <?php endif ?>
            <!--bairro-->
            <?php
			$bairro = Mage::getStoreConfig('onepagecheckout/address_form/address4');
			if ($bairro !== 'hidden') : ?>
                <!-- endereco-->
				<div class="full">
                    <label for="bairro" <?php if ( $bairro  === 'required' ){ echo 'class="required"'; }?> ><?php echo $this->__('Bairro') ?></label>
					<?php if($bairro === 'required') { echo ' <sup>*</sup> ';}?>
					<div class="data_area">
						<input type="text" id="billing:street4" name="billing[street][4]" value="<?php echo $this->htmlEscape($this->getBillAddress()->getStreet(4)) ?>" title="<?php echo $this->__('Bairro') ?>" class="input-text t1<?php if($bairro === 'required'){ echo ' required-entry';} ?>" />
					</div>
				</div>
            <?php endif; ?>













			 <?php

			$city_r = Mage::getStoreConfig('onepagecheckout/address_form/city');
			$state_r= Mage::getStoreConfig('onepagecheckout/address_form/state');
			?>
			<div class="two_fields"<?php if(($city_r === 'hidden' && $state_r === 'hidden')){echo ' style="display:none"';}?> >
			<?php if ($city_r !== 'hidden') : ?>
				<div class="short">
					<label for="billing:city"<?php if ($city_r === 'required'){ echo ' class="required" ';}?>>
						<?php echo $this->__('City') ?>
					</label>
					<?php if ($city_r === 'required'){ echo ' <sup>*</sup> ';}?>
					<div class="data_area">
						<input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" value="<?php echo $this->htmlEscape($this->getBillAddress()->getCity()) ?>" class="t1<?php if ($city_r === 'required'){ echo ' required-entry ';}?>" id="billing:city" />
					</div>
				</div>
			<?php endif; ?>
				<div class="short"<?php if($state_r === 'hidden'){ echo ' style="display:none" ';}?>>
					<label for="billing:region_id"<?php if($state_r === 'required'){ echo ' class="required" ';}?>>
						<?php echo $this->__('State / Province') ?>
					</label>
					<?php if($state_r === 'required'){ echo ' <sup>*</sup> ';}?>
					<div class="data_area">
						<select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select<?php if($state_r === 'required') { echo ' required-entry';}?>" style="display:none;">
							<option value=""><?php echo $this->__('Select One') ?></option>
						</select>
						<script type="text/javascript">
						//<![CDATA[
							$('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getBillAddress()->getRegionId() ?>");
						//]]>
						</script>
						<input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->htmlEscape($this->getBillAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="t1<?php if($state_r === 'required'){ echo ' required-entry';}?>" style="display:none;" />
					</div>
				</div>
			</div>
			<div class='clr'></div>


	        <?php
	        $country_r = Mage::getStoreConfig('onepagecheckout/address_form/country');
	        ?>
			<div class="full"<?php if($country_r === 'hidden'){ echo ' style="display:none" ';}?>>
				<label for="billing:country_id"<?php if($country_r === 'required') { echo ' class="required" ';}?>>
	        		<?php echo $this->__('Country') ?>
	        	</label>
	        	<?php if($country_r === 'required') { echo ' <sup>*</sup> ';}?>
				<div class="data_area">
					<?php echo $this->getBillingCountriesSelectBox() ?>
				</div>
			</div>


			<?php


			if (!$logged) :

				$dob	= $this->getLayout()->createBlock('onepagecheckout/widget_dob');
				$gender	= $this->getLayout()->createBlock('onepagecheckout/widget_gender');
				$taxvat = $this->getLayout()->createBlock('onepagecheckout/widget_taxvat');

				if ($dob->isEnabled() || $gender->isEnabled()){ ?>
					<div class="two_fields">
						<?php if ($dob->isEnabled()):	?>
						<div class="short">
							<?php
								echo $dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml();
							?>
						</div>
						<?php endif; ?>
						<?php if ($gender->isEnabled()):	?>
						<div class="short">
							<?php
								echo $gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml();
							?>
						</div>
						<?php endif ?>
					</div>
					<div class='clr'></div>
				<?php
				}

				if ($taxvat->isEnabled()){	?>
					<div class='full'>
						<?php
							echo $taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml();
						?>
					</div>
				<?php
				}
				$agc = Mage::helper('onepagecheckout')->isGuestCheckoutAllowed();
                $habilitarcad = Mage::getStoreConfig('onepagecheckout/general/habilitarcad');
				if ($habilitarcad)  //$agc ||
				{
				?>
				<ul>
					<li class="options">
						<input type="checkbox" name="billing[register_account]" value="1" title="<?php echo $this->__('Create an account for later use') ?>" id="billing:register_account" onclick="if(window.billing) billing.setCreateAccount(this.checked);"<?php if ($this->getBillAddress()->getRegisterAccount()):?> checked="checked"<?php endif;?> class="checkbox" />
						<label for="billing:register_account">
							<?php echo $this->__('Create an account for later use') ?>
						</label>
					</li>
				</ul>
				<?php
				}
				else
				{
				?>
					<input type="hidden" name="billing[register_account]" value="1"/>
				<?php
				}
				?>
				<div class="two_fields" id="register-customer-password" <?php if ($agc) { echo ' style="display: none;" '; } ?>>
					<div class="short">
						<label for="billing:customer_password" class="required">
							<?php echo $this->__('Password') ?>
						</label>
						<sup>*</sup>
						<div class="data_area">
							<input type="password" name="billing[customer_password]" id="billing:customer_password" title="<?php echo $this->__('Password') ?>" class="t1 required-entry validate-password" />
						</div>
					</div>
					<div class="short">
						<label for="billing:confirm_password" class="required">
							<?php echo $this->__('Confirm Password') ?>
						</label>
						<sup>*</sup>
						<div class="data_area">
							<input type="password" name="billing[confirm_password]" title="<?php echo $this->__('Confirm Password') ?>" id="billing:confirm_password" class="t1 required-entry validate-cpassword" />
						</div>
					</div>
					<div class='clr'></div>
				</div>
				<div class='clr'></div>
			<?php
			endif;
			?>
			<ul>
			<?php
			if ($logged && $has_addr){
			?>
				<li class="options">
					<input type="checkbox" class="checkbox" name="billing[save_in_address_book]" id="billing:save_in_address_book" value="1" title="<?php echo $this->__('Save in address book') ?>" <?php if ($this->getBillAddress()->getSaveInAddressBook()){ echo ' checked="checked" ';}?> />
					<label>
						<?php echo $this->__('Save in address book'); ?>
					</label>
				</li>
			<?php
			}
			else
			{
			?>
				<li class="no-display">
					<input type="hidden" value="1" name="billing[save_in_address_book]" />
				</li>
			<?php
			}
			?>
			</ul>
	    </div>

    <?php
    if (Mage::helper('onepagecheckout')->isShippingAddressAllowed() && $this->canShip()){
    ?>
    	<input type="hidden" name="billing[use_for_shipping]" id="billing:use_for_shipping" value="<?php echo ($this->isUseBillingAddressForShipping())?'1':'0'; ?>" />
    <?php
    }else{
    ?>
    	<input type="hidden" name="billing[use_for_shipping]" value="1" />
    <?php
    }
    ?>
	</div>
</div>

<script type="text/javascript">
//<![CDATA[
	var billing = new BillingAddress();
	RegionUpdater.prototype.setMarkDisplay = function(){};
	ZipUpdater.prototype._setPostcodeOptional = function(){};
	var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', countryRegions, undefined, 'billing:postcode');

    // Adicionar validacao de cpf e cnpj ao campo Taxvat
    Validation.add('validar_cpf', 'O CPF ou CNPJ informado \xE9 invalido', function(v){return validaCPF(v,0);});
//]]>
</script>




<script type="text/javascript">
//<![CDATA[

     /*One Step Checkout
     Verifica se tem value no cep
     */

      var temcep = $j('input[name*="[postcode]"]').val();
      if(temcep != ""){
          buscarEndereco('http://onestepcheckout.com.br/beta3/skin/','billing');
      }

//]]>
</script>