<?php
$logged		= $this->isCustomerLoggedIn();
$has_addr	= $this->customerHasAddresses();

if (!$this->getQuote()->isVirtual() && Mage::helper('onepagecheckout')->isShippingAddressAllowed())
{
?>
<ul>
    <li class="options">
        <input type="checkbox" class="checkbox" name="shipping[same_as_billing]" id="shipping:same_as_billing" value="1"<?php if($this->getShipAddress()->getSameAsBilling()){echo ' checked="checked" ';} ?> title="<?php echo $this->__('Ship to this address') ?>" onclick="shipping.setSameAsBilling(this.checked)" />
        <label>
        	<?php echo $this->__('Ship to this address') ?>
        </label>
    </li>
</ul>
<div id="ship_address_block" class="onepagecheckout_block"<?php if($this->getShipAddress()->getSameAsBilling()){echo 'style="display: none;"';}?>>
	<div class="op_block_title">
    	<?php echo $this->__('New Shipping Address') ?>
    </div>
    <div class="form_fields">
    <?php if ($has_addr){ ?>
		<div class="full">
			<label>
				<?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?>
			</label>
			<div class="data_area">
				<?php echo $this->getCustomerShipAddr() ?>
			</div>
		</div>
    <?php } ?>
        <div id="ship_form"<?php if ($has_addr){ echo ' style="display:none;" ';}?>>
			<input type="hidden" name="shipping[address_id]" id="shipping:address_id" value="<?php echo $this->getShipAddress()->getId() ?>" />
			<div class="two_fields">
				<?php echo $this->getLayout()->createBlock('onepagecheckout/widget_name')->setObject($this->getShipAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->setFieldParams('onchange="shipping.setSameAsBilling(false)"')->toHtml() ?>
			</div>
			<div class='clr'></div>
			<?php
			$cr = Mage::getStoreConfig('onepagecheckout/address_form/company');
			if ($cr !== 'hidden') : ?>
				<div class="full">
					<label>
						<?php echo $this->__('Company') ?>
					</label>
					<?php if ( $cr  === 'required' ){echo ' <sup>*<sup> ';} ?>
					<div class="data_area">
						<input type="text" id="shipping:company" name="shipping[company]" value="<?php echo $this->htmlEscape($this->getShipAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="t1<?php if( $cr === 'required' ){ echo ' required-entry ';} ?>" onchange="shipping.setSameAsBilling(false);" />
					</div>
				</div>
			<?php endif; ?>




			<?php
			$phone_r= Mage::getStoreConfig('onepagecheckout/address_form/phone');
			$fax_r	= Mage::getStoreConfig('onepagecheckout/address_form/fax');
			?>

            <?php if ($phone_r !== 'hidden' || $fax_r !== 'hidden' ) : ?>
            <div class="two_fields">

        				<?php if ($phone_r !== 'hidden') : ?>
        					<div class="short">
        						<label for="shipping:telephone"<?php if($phone_r === 'required') { echo ' class="required" ';}?>>
        							<?php echo $this->__('Telephone') ?>
        						</label>
        						<?php if($phone_r === 'required') { echo ' <sup>*</sup> ';}?>
        						<div class="data_area">
        							<input type="text" name="shipping[telephone]" value="<?php echo $this->htmlEscape($this->getBillAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="t1<?php if($phone_r === 'required') { echo ' required-entry ';}?>" id="shipping:telephone" />
        						</div>
        					</div>
        				<?php endif; ?>

            			<?php if ($fax_r !== 'hidden') : ?>
            				<div class="short">
            					<label for="shipping:fax"<?php if($fax_r === 'required') {echo ' class="required" ';}?>>
            						<?php echo $this->__('Fax') ?>
            					</label>
            					<?php if($fax_r === 'required') {echo ' <sup>*</sup> ';}?>
            					<div class="data_area">
            						<input type="text" name="shipping[fax]" value="<?php echo $this->htmlEscape($this->getBillAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="t1<?php if($fax_r === 'required') {echo ' required-entry ';}?>" id="shipping:fax" />
            					</div>
            				</div>
                        <?php endif ?>

            </div>
            <div class='clr'></div>
            <?php endif ?>




			<?php
			$zip_r	= Mage::getStoreConfig('onepagecheckout/address_form/zip');
			if ($zip_r !== 'hidden') :
			?>
					<div class="full">
						<label for="shipping:postcode"<?php if($zip_r === 'required'){echo ' class="required" ';}?>>
							<?php echo $this->__('Zip Code') ?>
						</label>
						<?php if($zip_r === 'required'){echo ' <sup>* (somente n&uacute;meros)</sup>';}?>
						<div class="data_area">
							<input maxlength="8" type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->htmlEscape($this->getShipAddress()->getPostcode()) ?>" class="t1 validate-zip-international<?php if($zip_r === 'required'){echo ' required-entry ';}?>" onchange="shipping.setSameAsBilling(false);" onblur="buscarEndereco('<?=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN)?>','shipping');"/>
						</div>
					</div>
			<?php endif; ?>






			<?php
			if ($ar !== 'hidden') :
                $campos = array("Endere&ccedil;o","N&uacute;mero","Complemento","Bairro");
				$csl	= "4";

				for ($i = 1; $i <= $csl; $i++){
				?>
                <div class="clr"></div>
				<div class="full">
					<label for="shipping:street<?php echo $i?>" class="required">
						<?php echo $campos[$i-1] ?>
					</label>
                    <sup>*</sup>
					<div class="data_area">
						<input type="text" name="shipping[street][<?php echo $i?>]" id="shipping:street<?php echo $i?>" title="<?php echo $campos[$i-1] ?>" value="<?php echo $this->htmlEscape($this->getShipAddress()->getStreet($i)) ?>" class="t1 required-entry" /> <!--  onchange="shipping.setSameAsBilling(false);" -->
					</div>
				</div>
             <?php } endif; ?>


			<?php


			$city_r = Mage::getStoreConfig('onepagecheckout/address_form/city');
			$state_r= Mage::getStoreConfig('onepagecheckout/address_form/state');
			?>
			<div class="two_fields"<?php if(($city_r === 'hidden' && $state_r === 'hidden')){echo ' style="display:none"';}?> >
			<?php if ($city_r !== 'hidden') : ?>
				<div class="short">
					<label>
						<?php echo $this->__('City') ?>
					</label>
					<?php if ($city_r === 'required'){ echo ' <sup>*</sup> ';}?>

					<div class="data_area">
						<input type="text" name="shipping[city]" id="shipping:city" title="<?php echo $this->__('City') ?>" value="<?php echo $this->htmlEscape($this->getShipAddress()->getCity()) ?>" class="t1<?php if ($city_r === 'required'){ echo ' required-entry ';}?>" onchange="shipping.setSameAsBilling(false);" />
					</div>
				</div>
			<?php endif; ?>
				<div class="short"<?php if($state_r === 'hidden'){ echo ' style="display:none" ';}?>>
					<label>
						<?php echo $this->__('State / Province') ?>
					</label>
					<div class="data_area">
						<select id="shipping:region_id" name="shipping[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select<?php if($state_r === 'required') { echo ' required-entry';}?>" style="display:none;">
							<option value=""><?php echo $this->__('Select One') ?></option>
						</select>
						<script type="text/javascript">
						//<![CDATA[
							$('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getShipAddress()->getRegionId() ?>");
						//]]>
						</script>
						<input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->htmlEscape($this->getShipAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="t1<?php if($state_r === 'required'){ echo ' required-entry';}?>" style="display:none;" />
					</div>
				</div>
			</div>
			<div class='clr'></div>






	        <?php
	        $country_r = Mage::getStoreConfig('onepagecheckout/address_form/country');
	        ?>
	        <div class="full"<?php if($country_r === 'hidden'){ echo ' style="display:none" ';}?>>
	        	<label>
	        		<?php echo $this->__('Country') ?>
	        	</label>
	        	<?php if($country_r === 'required') { echo ' <sup>*</sup> ';}?>
				<div class="data_area">
					<?php echo $this->getShippingCountriesSelectBox() ?>
				</div>
			</div>


			<ul>
			<?php
			if ($logged && $has_addr){
			?>
				<li class="options">
					<input type="checkbox" class="checkbox" name="shipping[save_in_address_book]" id="shipping:save_in_address_book" value="1" title="<?php echo $this->__('Save in address book') ?>" <?php if ($this->getShipAddress()->getSaveInAddressBook()){ echo ' checked="checked" ';}?> />
					<label>
						<?php echo $this->__('Save in address book') ?>
					</label>
				</li>
			<?php
			}
			else
			{
			?>
				<li class="no-display">
					<input type="hidden" name="shipping[save_in_address_book]" value="1" />
				</li>
			<?php
			}
			?>
			</ul>
        </div>
	</div>
</div>
<script type="text/javascript">
//<![CDATA[
	var shipping = new ShippingAddress('onepagecheckout_orderform');
	var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', countryRegions, undefined, 'shipping:postcode');
//]]>
</script>
<?php
}
?>
