<?php
/*=========================================================================================================================================================
 *
 *  PROJETO OSC MAGENTO BRASIL - VERSÃO FINAL V3.0
 *  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 *  O módulo One Step Checkout normatizado para a localização brasileira.
 *  site do projeto: http://onestepcheckout.com.br/
 *  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 *
 *
 *
 *  Mmantenedores do Projeto:
 *  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 *
 *  Deivison Arthur Lemos Serpa
 *  deivison.arthur@gmail.com
 *  www.deivison.com.br
 *  (21)9203-8986
 *
 *  Denis Colli Spalenza
 *  http://www.xpdev.com.br
 *
 *  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 *
 *
 *
 *  GOSTOU DO MÓDULO?
 *  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 *  Se você gostou, se foi útil para você, se fez você economizar aquela grana pois estava prestes a pagar caro por aquele módulo pago, pois não achava uma
 *  solução gratuita que te atendesse e queira prestigiar o trabalho feito efetuando uma doação de qualquer valor, não vou negar e vou ficar grato! você
 *  pode fazer isso visitando a página do projeto em: http://onestepcheckout.com.br/
 *  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 *
/*=========================================================================================================================================================
 */

$logged		= $this->isCustomerLoggedIn();
$has_addr	= $this->customerHasAddresses();

if (!$this->getQuote()->isVirtual() && Mage::helper('onepagecheckout')->isShippingAddressAllowed())
{
?>
<ul>
    <li class="options">
        <input type="checkbox" class="checkbox" name="shipping[same_as_billing]" id="shipping:same_as_billing" value="1"<?php if($this->getShipAddress()->getSameAsBilling()){echo ' checked="checked" ';} ?> title="<?php echo $this->__('Ship to this address') ?>" onclick="shipping.setSameAsBilling(this.checked)" />
        <label for="shipping:same_as_billing">
        	<?php echo $this->__('Ship to this address') ?>
        </label>
    </li>
</ul>
<div id="ship_address_block" class="onepagecheckout_block"<?php if($this->getShipAddress()->getSameAsBilling()){echo 'style="display: none;"';}?>>
	<div class="op_block_title">
    	<?php echo $this->__('New Shipping Address') ?>
    </div>
    <div class="form_fields">
    <?php if ($has_addr){ ?>
		<div class="full">
			<label>
				<?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?>
			</label>
			<div class="data_area">
				<?php echo $this->getCustomerShipAddr() ?>
			</div>
		</div>
    <?php } ?>
        <div id="ship_form"<?php if ($has_addr){ echo ' style="display:none;" ';}?>>
			<input type="hidden" name="shipping[address_id]" id="shipping:address_id" value="<?php echo $this->getShipAddress()->getId() ?>" />
			<div class="two_fields">
				<?php echo $this->getLayout()->createBlock('onepagecheckout/widget_name')->setObject($this->getShipAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->setFieldParams('onchange="shipping.setSameAsBilling(false)"')->toHtml() ?>
			</div>



			<?php
			$cr = Mage::getStoreConfig('onepagecheckout/address_form/company');
			if ($cr !== 'hidden') : ?>
				<div class="full">
					<label>
						<?php echo $this->__('Company') ?>
					<?php if ( $cr  === 'required' ){echo ' <sup>*<sup> ';} ?>
                    </label>
					<div class="data_area">
						<input type="text" id="shipping:company" name="shipping[company]" value="<?php echo $this->htmlEscape($this->getBillAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="t1<?php if( $cr === 'required' ){ echo ' required-entry ';} ?>" />   <!-- onchange="shipping.setSameAsBilling(false);"  -->
					</div>
				</div>
			<?php endif; ?>







			<?php
			$rgientrega = Mage::getStoreConfig('onepagecheckout/outrasopcoes/rgientrega');
			if ($rgientrega !== 'hidden') : ?>
				<div class="full">
					<label>
						<?php echo $this->__('Identidade (RG) para a Entrega') ?>
					<?php if ( $rgientrega  === 'required' ){echo ' <sup>*<sup> ';} ?>
                    </label>
					<div class="data_area">
						<input type="text" id="rgientrega" name="shipping[rg]" value="<?php echo $this->htmlEscape($this->getBillAddress()->getRg()) ?>" title="<?php echo $this->__('Identidade (RG) para a  Entrega') ?>" class="t1<?php if( $rgientrega === 'required' ){ echo ' required-entry ';} ?>"  />
					</div>
				</div>
			<?php endif; ?>


            <!--cpf-->
			<?php
			$cpfentrega = Mage::getStoreConfig('onepagecheckout/outrasopcoes/cpfentrega');
			if ($cpfentrega !== 'hidden') : ?>
				<div class="full">
					<label>
						<?php echo $this->__('CPF/CNPJ para a  Entrega') ?>
					<?php if ( $cpfentrega  === 'required' ){echo ' <sup>*<sup> ';} ?>
                    </label>
					<div class="data_area">
						<input type="text" id="cpfentrega" name="shipping[cpfcnpj]" value="<?php echo $this->htmlEscape($this->getBillAddress()->getCpfcnpj()) ?>" title="<?php echo $this->__('CPF/CNPJ para a  Entrega') ?>" class="input-text validar_cpf  t1<?php if( $cpfentrega === 'required' ){ echo ' required-entry ';} ?>"  />
					</div>
				</div>
			<?php endif; ?>

            <!--cpf Taxvat-->
            <?php
			$cpfcnpjtaxvat = Mage::getStoreConfig('onepagecheckout/address_form/cpfcnpjtaxvat');
			if ($cpfcnpjtaxvat !== 'hidden') : ?>
                <!-- CNPJ e CPF shipping:taxvat-->
				<div class="full">
                    <label for="shipping:taxvat" <?php if ( $cpfcnpjtaxvat  === 'required' ){ echo 'class="required"'; }?> >
						<?php echo $this->__('Taxvat') ?>
					</label>
					<?php if($cpfcnpjtaxvat === 'required') { echo ' <sup>*</sup> ';}?>
					<div class="data_area">
						<input type="text" id="shipping:taxvat" name="shipping[taxvat]" value="<?php echo $this->htmlEscape($this->getCustomer()->getCpfcnpj()) ?>" title="<?php echo $this->__('Taxvat') ?>" class="validar_cpf t1<?php if($cpfcnpjtaxvat === 'required'){ echo ' required-entry';} ?>" />
					</div>
				</div>
            <?php endif; ?>



           <div class='clr'></div>

			<?php
			$phone_r= Mage::getStoreConfig('onepagecheckout/address_form/phone');
			$fax_r	= Mage::getStoreConfig('onepagecheckout/address_form/fax');
			?>

            <?php if ($phone_r !== 'hidden' || $fax_r !== 'hidden' ) : ?>
            <div class="two_fields">
        				<?php if ($phone_r !== 'hidden') : ?>
        					<div class="short">
        						<label for="shipping:telephone"<?php if($phone_r === 'required') { echo ' class="required" ';}?>>
        							<?php echo $this->__('Telephone') ?>

        						<?php if($phone_r === 'required') { echo ' <sup>*</sup> ';}?>
                                </label>
        						<div class="data_area">
        							<input type="text" name="shipping[telephone]" value="<?php echo $this->htmlEscape($this->getBillAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="t1<?php if($phone_r === 'required') { echo ' required-entry ';}?>" id="shipping:telephone" />
        						</div>
        					</div>
        				<?php endif; ?>

            			<?php if ($fax_r !== 'hidden') : ?>
            				<div class="short">
            					<label for="shipping:fax"<?php if($fax_r === 'required') {echo ' class="required" ';}?>>
            						<?php echo $this->__('Fax') ?>
            					<?php if($fax_r === 'required') {echo ' <sup>*</sup> ';}?>
                                </label>
            					<div class="data_area">
            						<input type="text" name="shipping[fax]" value="<?php echo $this->htmlEscape($this->getBillAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="t1<?php if($fax_r === 'required') {echo ' required-entry ';}?>" id="shipping:fax" />
            					</div>
            				</div>
                        <?php endif ?>

            </div>
            <div class='clr'></div>
            <?php endif ?>
			<?php
			$tracoAtivo = Mage::getStoreConfig('onepagecheckout/general/tracoativo');

			$zip_r	= Mage::getStoreConfig('onepagecheckout/address_form/zip');
			if ($zip_r !== 'hidden') :
			?>
					<div class="full">
						<label for="shipping:postcode"<?php if($zip_r === 'required'){echo ' class="required" ';}?>>
							<?php echo $this->__('Zip Code') ?>
						</label>
						<?php if($zip_r === 'required'){echo ' <sup>* (somente n&uacute;meros)</sup>';}?>
						<div class="data_area">
							<input maxlength="8" type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->htmlEscape($this->getShipAddress()->getPostcode()) ?>" class="t1 validate-zip-international<?php if($zip_r === 'required'){echo ' required-entry ';}?> <?php if($tracoAtivo === '1'){ echo ' tracoAtivo';} ?>   " onchange="shipping.setSameAsBilling(false);" onblur="buscarEndereco('<?=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN)?>','shipping');"/>
						</div>
					</div>
			<?php endif; ?>










            <!--enderecao-->
            <?php
			$endereco = Mage::getStoreConfig('onepagecheckout/address_form/address');
			if ($endereco !== 'hidden') : ?>
                <!-- endereco-->
                <div class="clr"></div>
				<div class="full">
                    <label for="endereco" <?php if ( $endereco  === 'required' ){ echo 'class="required"'; }?> ><?php echo $this->__('Endere&ccedil;o') ?></label>
					<?php if($endereco === 'required') { echo ' <sup>*</sup> ';}?>
					<div class="data_area">
						<input type="text" id="shipping:street1" name="shipping[street][1]" value="<?php echo $this->htmlEscape($this->getBillAddress()->getStreet(1)) ?>" title="<?php echo $this->__('Endere&ccedil;o') ?>" class="input-text t1<?php if($endereco === 'required'){ echo ' required-entry';} ?>" />
					</div>
				</div>
            <?php endif; ?>
            <!--Numero e Complemento-->
			<?php
			$complemento = Mage::getStoreConfig('onepagecheckout/address_form/address3');
            $numero = Mage::getStoreConfig('onepagecheckout/address_form/address2');
			?>

            <?php if ($numero !== 'hidden' || $complemento !== 'hidden' ) : ?>
            <div class="two_fields">

        				<?php if ($numero !== 'hidden') : ?>
        					<div class="short">
        						<label for="shipping:street2"<?php if($numero === 'required') { echo ' class="required" ';}?>>
        							<?php echo $this->__('N&uacute;mero') ?>
        						</label>
        						<?php if($numero === 'required') { echo ' <sup>*</sup> ';}?>
        						<div class="data_area">
            						<input type="text" id="shipping:street2" name="shipping[street][2]" value="<?php echo $this->htmlEscape($this->getBillAddress()->getStreet(2)) ?>" title="<?php echo $this->__('N&uacute;mero') ?>" class="input-text t1<?php if($numero === 'required'){ echo ' required-entry';} ?>" />
        						</div>
        					</div>
        				<?php endif; ?>

            			<?php if ($complemento !== 'hidden') : ?>
            				<div class="short">
            					<label for="shipping:street3"<?php if($complemento === 'required') {echo ' class="required" ';}?>>
            						<?php echo $this->__('Complemento') ?>
            					</label>
            					<?php if($complemento === 'required') {echo ' <sup>*</sup> ';}?>
            					<div class="data_area">
            						<input type="text" id="shipping:street3" name="shipping[street][3]" value="<?php echo $this->htmlEscape($this->getBillAddress()->getStreet(3)) ?>" title="<?php echo $this->__('Complemento') ?>" class="input-text t1<?php if($complemento === 'required'){ echo ' required-entry';} ?>" />
            					</div>
            				</div>
                        <?php endif ?>
            </div>
            <div class='clr'></div>
            <?php endif ?>
            <!--bairro-->
            <?php
			$bairro = Mage::getStoreConfig('onepagecheckout/address_form/address4');
			if ($bairro !== 'hidden') : ?>
                <!-- endereco-->
				<div class="full">
                    <label for="bairro" <?php if ( $bairro  === 'required' ){ echo 'class="required"'; }?> ><?php echo $this->__('Bairro') ?></label>
					<?php if($bairro === 'required') { echo ' <sup>*</sup> ';}?>
					<div class="data_area">
						<input type="text" id="shipping:street4" name="shipping[street][4]" value="<?php echo $this->htmlEscape($this->getBillAddress()->getStreet(4)) ?>" title="<?php echo $this->__('Bairro') ?>" class="input-text t1<?php if($bairro === 'required'){ echo ' required-entry';} ?>" />
					</div>
				</div>
            <?php endif; ?>

























			<?php


			$city_r = Mage::getStoreConfig('onepagecheckout/address_form/city');
			$state_r= Mage::getStoreConfig('onepagecheckout/address_form/state');
			?>
			<div class="two_fields"<?php if(($city_r === 'hidden' && $state_r === 'hidden')){echo ' style="display:none"';}?> >
			<?php if ($city_r !== 'hidden') : ?>
				<div class="short">
					<label>
						<?php echo $this->__('City') ?>
					</label>
					<?php if ($city_r === 'required'){ echo ' <sup>*</sup> ';}?>

					<div class="data_area">
						<input type="text" name="shipping[city]" id="shipping:city" title="<?php echo $this->__('City') ?>" value="<?php echo $this->htmlEscape($this->getBillAddress()->getCity()) ?>" class="t1<?php if ($city_r === 'required'){ echo ' required-entry ';}?>" onchange="shipping.setSameAsBilling(false);" />
					</div>
				</div>
			<?php endif; ?>
				<div class="short"<?php if($state_r === 'hidden'){ echo ' style="display:none" ';}?>>
					<label>
						<?php echo $this->__('State / Province') ?>
					</label>
					<div class="data_area">
						<select id="shipping:region_id" name="shipping[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select<?php if($state_r === 'required') { echo ' required-entry';}?>" style="display:none;">
							<option value=""><?php echo $this->__('Select One') ?></option>
						</select>
						<script type="text/javascript">
						//<![CDATA[
							$('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getBillAddress()->getRegionId() ?>");
						//]]>
						</script>
						<input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->htmlEscape($this->getBillAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="t1<?php if($state_r === 'required'){ echo ' required-entry';}?>" style="display:none;" />
					</div>
				</div>                                                                                                            <!-- getShipAddress -->
			</div>
			<div class='clr'></div>






	        <?php
	        $country_r = Mage::getStoreConfig('onepagecheckout/address_form/country');
	        ?>
	        <div class="full"<?php if($country_r === 'hidden'){ echo ' style="display:none" ';}?>>
	        	<label>
	        		<?php echo $this->__('Country') ?>
	        	</label>
	        	<?php if($country_r === 'required') { echo ' <sup>*</sup> ';}?>
				<div class="data_area">
					<?php echo $this->getShippingCountriesSelectBox() ?>
				</div>
			</div>


			<ul>
			<?php
			if ($logged && $has_addr){
			?>
				<li class="options">
					<input type="checkbox" class="checkbox" name="shipping[save_in_address_book]" id="shipping:save_in_address_book" value="1" title="<?php echo $this->__('Save in address book') ?>" <?php if ($this->getShipAddress()->getSaveInAddressBook()){ echo ' checked="checked" ';}?> />
					<label>
						<?php echo $this->__('Save in address book') ?>
					</label>
				</li>
			<?php
			}
			else
			{
			?>
				<li class="no-display">
					<input type="hidden" name="shipping[save_in_address_book]" value="1" />
				</li>
			<?php
			}
			?>
			</ul>
        </div>
	</div>
</div>
<script type="text/javascript">
//<![CDATA[
	var shipping = new ShippingAddress('onepagecheckout_orderform');
	var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', countryRegions, undefined, 'shipping:postcode');




    // Adicionar validacao de cpf e cnpj ao campo Taxvat
    Validation.add('validar_cpf', 'O CPF ou CNPJ informado \xE9 invalido', function(v){return validaCPF(v,0);});

//]]>
</script>
<?php
}
?>
