<label for="<?php echo $this->getFieldId('month')?>"<?php if ($this->isRequired()) echo ' class="required"' ?>>
	<?php echo $this->__('Date of Birth') ?>
</label>
<?php echo '<sup>*</sup>' ?>
<div style="height: 39px !important;">
<div class="clr"></div>
<?php
    $this->setDateInput('d',
        '<div class="short dob-day" style="height: 39px !important; width: 25px !important; display: block !important; margin-bottom; 0px; margin-right: 10px">
             <input type="text" style="margin-bottom; 0px" id="' . $this->getFieldId('day') . '" name="' . $this->getFieldName('day') . '" value="' . $this->getDay() . '" title="' . $this->__('Day') . '" class="t1 input-text validate-custom" ' . $this->getFieldParams() . ' />
             <label for="' . $this->getFieldId('day') . '">' . $this->__('DD') . '</label>
         </div>'
    );

    $this->setDateInput('m',
        '<div class="short dob-month" style="height: 39px !important; width: 25px !important; display: block; float: left !important; margin-bottom; 0px; margin-right: 10px">
             <input type="text" style="margin-bottom; 0px" id="' . $this->getFieldId('month') . '" name="' . $this->getFieldName('month') . '" value="' . $this->getMonth()  . '" title="' . $this->__('Month')  . '" class="t1 input-text validate-custom" ' . $this->getFieldParams()  . ' />
             <label for="' . $this->getFieldId('month') . '">' . $this->__('MM')  . '</label>
         </div>'
    );

    $this->setDateInput('y',
        '<div class="short dob-year" style="height: 39px !important; width: 40px !important; display: block; float: left !important; margin-bottom; 0px">
             <input type="text" style="margin-bottom; 0px" id="' . $this->getFieldId('year') . '" name="' . $this->getFieldName('year') . '" value="' . $this->getYear()  . '" title="' . $this->__('Year')  . '" class="t1 input-text validate-custom" ' . $this->getFieldParams()  . ' />
             <label for="' . $this->getFieldId('year') . '">' . $this->__('YYYY')  . '</label>
         </div>'
    );

    echo $this->getSortedDateInputs()
?>

    <div class="dob-full" style="display:none;">
        <input type="hidden" id="dob" name="dob">
    </div>

    <div class="validation-advice" style="display:none;">Este é um campo obrigatório.</div>
</div>
<script type="text/javascript">
//<![CDATA[
    var customer_dob = new Varien.DOB('.customer-dob', <?php echo $this->isRequired() ? 'true' : 'false' ?>, '<?php echo $this->getDateFormat() ?>');
//]]>
</script>
