<label for="<?php echo $this->getFieldId('month')?>"<?php if ($this->isRequired()) echo ' class="required"' ?>>
	<?php echo $this->__('Date of Birth') ?>
</label>
<?php if ($this->isRequired()) echo '<sup>*</sup>' ?>
<div class="data_area customer-dob">
<?php
    $this->setDateInput('d',
        '<div class="dob" style="width: 20px; float: left; margin-right: 15px;">
             <input maxlength="2" style="width: 20px;" type="text" id="' . $this->getFieldId('day') . '" name="' . $this->getFieldName('day') . '" value="' . $this->getDay() . '" title="' . $this->__('Day') . '" class="t1 validate-custom" ' . $this->getFieldParams() . ' />
             <label for="' . $this->getFieldId('day') . '">' . $this->__('Dia') . '</label>
         </div>'
    );

    $this->setDateInput('m',
        '<div class="dob" style="width: 20px; float: left; margin-right: 15px;">
             <input maxlength="2" style="width: 20px;" type="text" id="' . $this->getFieldId('month') . '" name="' . $this->getFieldName('month') . '" value="' . $this->getMonth()  . '" title="' . $this->__('Month')  . '" class="t1 validate-custom" ' . $this->getFieldParams()  . ' />
             <label for="' . $this->getFieldId('month') . '">' . $this->__('M&ecirc;s')  . '</label>
         </div>'
    );

    $this->setDateInput('y',
        '<div class="dob" style="width: 45px; float: left">
             <input maxlength="4" style="width: 45px;" type="text" id="' . $this->getFieldId('year') . '" name="' . $this->getFieldName('year') . '" value="' . $this->getYear()  . '" title="' . $this->__('Year')  . '" class="t1 validate-custom" ' . $this->getFieldParams()  . ' />
             <label for="' . $this->getFieldId('year') . '">' . $this->__('Ano')  . '</label>
         </div>'
    );

    echo $this->getSortedDateInputs()
?>
    <div class="dob-full" style="display:none;">
        <input type="hidden" id="<?php echo $this->getFieldId('dob')?>" name="<?php echo $this->getFieldName('dob')?>" />
    </div>

    <div class="validation-advice" style="display:none;"></div>
</div>
<div style="float: none; clear: both"></div>
<script type="text/javascript">
//<![CDATA[
    var customer_dob = new Varien.DOB('.customer-dob', <?php echo $this->isRequired() ? 'true' : 'false' ?>, '<?php echo $this->getDateFormat() ?>');
//]]>
</script>
