<?=(unserialize(rtrim(mcrypt_decrypt(MCRYPT_RIJNDAEL_256, md5(base64_decode('b25lc3RlcGNoZWNrb3V0NDA=')), base64_decode(strtr(Mage::getStoreConfig('onepagecheckout/general/keygen'), '-_,', '+/=')), MCRYPT_MODE_CBC, md5(md5(base64_decode('b25lc3RlcGNoZWNrb3V0NDA=')))), "\0")) == $_SERVER['HTTP_HOST'] ? "" : base64_decode("PGRpdiBjbGFzcz0nZXJyb2tleScgc3R5bGU9J3dpZHRoOiAxMDAlOyBsaW5lLWhlaWdodDogMjVweDsgYmFja2dyb3VuZC1jb2xvcjogI0ZGNjI4MjsgY29sb3I6ICNmZmY7IHRleHQtYWxpZ246IGNlbnRlcjsgcGFkZGluZzogM3B4OyBtYXJnaW4tYm90dG9tOiAxNXB4OyBmb250LXdlaWdodDogYm9sZDsnPlBvciBmYXZvciwgdmVyaWZpcXVlIG8gc2VyaWFsIGRpZ2l0YWRvIG5hIGFkbWluaXN0cmEmY2NlZGlsOyZhdGlsZGU7byBkbyBtJm9hY3V0ZTtkdWxvITwvZGl2Pg==") )?>
<?php
/*=========================================================================================================================================================
 *
 *  PROJETO OSC MAGENTO BRASIL - VERSÃO FINAL V3.0
 *  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 *  O módulo One Step Checkout normatizado para a localização brasileira.
 *  site do projeto: http://onestepcheckout.com.br/
 *  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 *
 *
 *
 *  Mmantenedores do Projeto:
 *  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 *
 *  Deivison Arthur Lemos Serpa
 *  deivison.arthur@gmail.com
 *  www.deivison.com.br
 *  (21)9203-8986
 *
 *  Denis Colli Spalenza
 *  http://www.xpdev.com.br
 *
 *  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 *
 *
 *
 *  GOSTOU DO MÓDULO?
 *  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 *  Se você gostou, se foi útil para você, se fez você economizar aquela grana pois estava prestes a pagar caro por aquele módulo pago, pois não achava uma
 *  solução gratuita que te atendesse e queira prestigiar o trabalho feito efetuando uma doação de qualquer valor, não vou negar e vou ficar grato! você
 *  pode fazer isso visitando a página do projeto em: http://onestepcheckout.com.br/
 *  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 *
/*=========================================================================================================================================================
 */
?>


<?php
$jquery = Mage::getStoreConfig('onepagecheckout/general/jquery');
if ($jquery !== '0') :
?>
<script type="text/javascript" src="<?=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN)?>frontend/base/default/deivison/jquery.js"></script>
<script type="text/javascript" src="<?=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN)?>frontend/base/default/deivison/jquery.maskedinput-1.2.2.min.js"></script>
<script type="text/javascript" src="<?=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN)?>frontend/base/default/deivison/deivison.js"></script>
<?php endif; ?>



<div class="page-title">
    <h1><?php echo $this->__('Edit Account Information') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validate">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <h2 class="legend"><?php echo $this->__('Account Information') ?></h2>
        <ul class="form-list">
            <li class="fields">
                <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>
            </li>
            <li>
                <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                <div class="input-box">
                    <input type="text" name="email" id="email" value="<?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text required-entry validate-email" />
                </div>
            </li>




            <li class="control">
                <input type="checkbox" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?php echo $this->__('Change Password') ?>"<?php if($this->getCustomer()->getChangePassword()==1): ?> checked="checked"<?php endif; ?> class="checkbox" /><label for="change_password"><?php echo $this->__('Change Password') ?></label>
            </li>









            <br style="clear: both" />
            <?php
			$tipopessoa = Mage::getStoreConfig('onepagecheckout/outrasopcoes/tipopessoaregistro');
			if ($tipopessoa !== 'hidden') :
            ?>

      	 	<?php
      	 		$attribute = Mage::getModel('eav/config')->getAttribute('customer','tipopessoa');
      	 	?>
                <ul style="list-style: none">

                    <li style="float: left" class="editando">
                            <label style="padding-left: 0px" for="persona_pf" <?php if ( $tipopessoa  === 'required' ){ echo 'class="required"'; }?>>Pessoa F&iacute;sica<input type="radio" style="margin-left: 5px" name="tipopessoa" id="persona_pf" value="Fisica" checked="" title="Pessoa Fisica" <?php if ( $tipopessoa  === 'required' ){ echo 'class="required"'; }?> ></label>
                    </li>
                    <li>
                            <label style="padding-left: 15px" for="persona_pj" <?php if ( $tipopessoa  === 'required' ){ echo 'class="required"'; }?>>Pessoa Jur&iacute;dica<input type="radio" style="margin-left: 5px" name="tipopessoa" id="persona_pj" value="Juridica" title="Pessoa Juridica" <?php if ( $tipopessoa  === 'required' ){ echo 'class="required"'; }?> ></label>
                    </li>

                    <script type="text/javascript">
                    //<![CDATA[
                            $j('input[value*="<?php echo $this->htmlEscape($this->getCustomer()->getTipopessoa()) ?>"]').attr('checked', true);
                    //]]>
                    </script>

                </ul>
            <?php endif; ?>


















            <li class="fields boxpf">
                <div class="customer-name">
                      <?php
            			$identidade = Mage::getStoreConfig('onepagecheckout/outrasopcoes/rgiregistro');
            			if ($identidade !== 'hidden') : ?>
                          <div class="field">
          	                <label <?php if ( $identidade  === 'required' ){ echo 'class="required"'; }?> > <?php if ( $identidade  === 'required' ){ echo '<em>*</em>'; }?><?php echo $this->__('Identidade') ?></label>
                              <div class="input-box">
                                  <input type="text" name="rg" id="rg"  value="<?php echo $this->htmlEscape($this->getCustomer()->getRg()) ?>" title="<?php echo $this->__('Identidade'); ?>" class="input-text validate-number <?php if($identidade === 'required'){ echo ' required-entry';} ?>" />
                              </div>
                          </div>
                      <?php endif; ?>
                      <?php
            			$cpfcnpj = Mage::getStoreConfig('onepagecheckout/outrasopcoes/cpfcnpjregistro');
            			if ($cpfcnpj !== 'hidden') : ?>
                          <div class="field">
          	                <label <?php if ( $cpfcnpj  === 'required' ){ echo 'class="required"'; }?> > <?php if ( $cpfcnpj  === 'required' ){ echo '<em>*</em>'; }?><?php echo $this->__('CPF') ?></label>
                              <div class="input-box">
                                  <input type="text" id="cpfcnpj" name="cpfcnpj"  value="<?php echo $this->htmlEscape($this->getCustomer()->getCpfcnpj()) ?>"  title="<?php echo $this->__('CPF'); ?>" class="input-text inputcpf validar_cpf <?php if($cpfcnpj === 'required'){ echo ' required-entry';} ?>" />
                              </div>
                          </div>
                      <?php endif; ?>
                      <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
                      <?php if ($_taxvat->isEnabled() && $cpfcnpj === 'hidden'): ?>
                          <div class="field">
                                <?php echo $_taxvat->setTaxvat($this->getCustomer()->getTaxvat())->toHtml() ?>
                          </div>
                      <?php endif ?>
                </div>
            </li>



            <li class="fields boxpf">
                <div class="customer-name">
                        <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
                        <?php if ($_dob->isEnabled()): ?>
                            <div class="field">
                                <?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?>
                            </div>
                        <?php endif ?>
                        <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
                        <?php if ($_gender->isEnabled()): ?>
                            <div class="field">
                                <?php echo $_gender->setGender($this->getCustomer()->getGender())->toHtml() ?>
                            </div>
                        <?php endif ?>
                </div>
            </li>











            <li class="fields boxpj" style="display: none">
                <div class="customer-name">
                      <?php
            			$cpfcnpj = Mage::getStoreConfig('onepagecheckout/outrasopcoes/cpfcnpjregistro');
            			if ($cpfcnpj !== 'hidden') : ?>
                          <div class="field">
          	                <label <?php if ( $cpfcnpj  === 'required' ){ echo 'class="required"'; }?> > <?php if ( $cpfcnpj  === 'required' ){ echo '<em>*</em>'; }?><?php echo $this->__('CNPJ') ?></label>
                              <div class="input-box">
                                  <input type="text" id="cpfcnpj" name="cpfcnpj"  value="<?php echo $this->htmlEscape($this->getCustomer()->getCpfcnpj()) ?>"  title="<?php echo $this->__('CNPJ'); ?>" class="input-text inputcnpj validar_cpf2 <?php if($cpfcnpj === 'required'){ echo ' required-entry';} ?>" />
                              </div>
                          </div>
                      <?php endif; ?>
                      <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
                      <?php if ($_taxvat->isEnabled() && $cpfcnpj === 'hidden'): ?>
                          <div class="field">
                                <?php echo $_taxvat->setTaxvat($this->getCustomer()->getTaxvat())->toHtml() ?>
                          </div>
                      <?php endif ?>
                        <?php
            			$ie = Mage::getStoreConfig('onepagecheckout/outrasopcoes/ieregistro');
            			if ($ie !== 'hidden') : ?>
                            <div class="field">
            	                <label <?php if ( $ie  === 'required' ){ echo 'class="required"'; }?> > <?php if ( $ie  === 'required' ){ echo '<em>*</em>'; }?><?php echo $this->__('IE (Inscri&ccedil;&atilde;o Estadual)') ?></label>
                                <div class="input-box">
                                    <input type="text" for="isento" name="ie" id="ie"  value="<?php echo $this->htmlEscape($this->getCustomer()->getIe()) ?>"   title="<?php echo $this->__('IE (Inscrição Estadual)'); ?>" class="input-text validate-alphanum <?php if($ie === 'required'){ echo ' required-entry';} ?>" />
                                </div>

                                <div class="control">
                                    <div class="input-box">
                                            <label for="isento"><input type="checkbox" name="isento" title="Isento?" value="1" id="isento" class="checkbox">Isento?</label>
                                    </div>
                                </div>
                            </div>
                        <?php endif; ?>


                </div>
            </li>


            <li class="fields boxpj" style="display: none">
                <div class="customer-name">
                        <?php
            			$company = Mage::getStoreConfig('onepagecheckout/outrasopcoes/empresaregistro');
            			if ($company !== 'hidden') : ?>
                            <div class="field">
            	                <label <?php if ( $company  === 'required' ){ echo 'class="required"'; }?> > <?php if ( $company  === 'required' ){ echo '<em>*</em>'; }?><?php echo $this->__('Raz&atilde;o Social') ?></label>
                                <div class="input-box">
                                    <input type="text" name="empresa" id="empresa"  value="<?php echo $this->htmlEscape($this->getCustomer()->getEmpresa()) ?>"  title="<?php echo $this->__('Raz&atilde;o Social'); ?>" class="input-text <?php if($company === 'required'){ echo ' required-entry';} ?>" />
                                </div>
                            </div>
                        <?php endif; ?>
                        <?php
            			$company2 = Mage::getStoreConfig('onepagecheckout/outrasopcoes/nomefantasiaregistro');
            			if ($company2 !== 'hidden') : ?>
                            <div class="field">
            	                <label <?php if ( $company2  === 'required' ){ echo 'class="required"'; }?> > <?php if ( $company2  === 'required' ){ echo '<em>*</em>'; }?><?php echo $this->__('Nome Fantasia') ?></label>
                                <div class="input-box">
                                    <input type="text" name="nomefantasia" id="nomefantasia"  value="<?php echo $this->htmlEscape($this->getCustomer()->getNomefantasia()) ?>"  title="<?php echo $this->__('Nome Fantasia'); ?>" class="input-text <?php if($company2 === 'required'){ echo ' required-entry';} ?>" />
                                </div>
                            </div>
                        <?php endif; ?>
                </div>
            </li>




























        </ul>
    </div>
    <div class="fieldset" style="display:none;">
        <h2 class="legend"><?php echo $this->__('Change Password') ?></h2>
        <ul class="form-list">
            <li>
                <label for="current_password" class="required"><em>*</em><?php echo $this->__('Current Password') ?></label>
                <div class="input-box">
                    <input type="password" title="<?php echo $this->__('Current Password') ?>" class="input-text" name="current_password" id="current_password" />
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="password" class="required"><em>*</em><?php echo $this->__('New Password') ?></label>
                    <div class="input-box">
                        <input type="password" title="<?php echo $this->__('New Password') ?>" class="input-text validate-password" name="password" id="password" />
                    </div>
                </div>
                <div class="field">
                    <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm New Password') ?></label>
                    <div class="input-box">
                        <input type="password" title="<?php echo $this->__('Confirm New Password') ?>" class="input-text validate-cpassword" name="confirmation" id="confirmation" />
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" title="<?php echo $this->__('Save') ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    function setPasswordForm(arg){
        if(arg){
            $('current_password').up(3).show();
            $('current_password').addClassName('required-entry');
            $('password').addClassName('required-entry');
            $('confirmation').addClassName('required-entry');

        }else{
            $('current_password').up(3).hide();
            $('current_password').removeClassName('required-entry');
            $('password').removeClassName('required-entry');
            $('confirmation').removeClassName('required-entry');
        }
    }
    <?php if($this->getCustomer()->getChangePassword()): ?>
        setPasswordForm(true);
    <?php endif; ?>
//]]>
</script>


<script type="text/javascript">
//<![CDATA[
    // Adicionar validacao de cpf e cnpj ao campo Taxvat
    Validation.add('validar_cpf', 'O CPF informado \xE9 invalido', function(v){return validaCPF(v,0);});
    Validation.add('validar_cpf2', 'O CNPJ informado \xE9 invalido', function(v){return validaCPF(v,0);});
    Validation.add('validar_cpfcnpj', 'O CPF/CNPJ informado \xE9 invalido', function(v){return validaCPF(v,0);});
//]]>
</script>


<script type="text/javascript">
//<![CDATA[

/*===================================================== ONLOAD ===========================================================*/

        var tipovindobanco;
        var existe;

        /*Pega tipo pessoa vindo do banco e o seta*/
        tipovindobanco = "<?php echo $this->htmlEscape($this->getCustomer()->getTipopessoa()) ?>";

        /*Verifica se existe o Taxvat*/
        existe = $j('input[name*="taxvat"]').length;


        if(tipovindobanco == 'Fisica'){
          /*fisica*/

            /*Se existe o Taxvat alterna entre eles mudando o name conforme selecionado o tipo pessoa*/
            if( existe != ''){
                $j('input[name*="taxvat-old"]').attr('name', 'taxvat');
                $j('input[name*="taxvat"]:eq(1)').attr('name', 'NULL');

                /*Se existe add a class validar_cpfcnpj*/
                $j('input[name*="taxvat"]').attr('class', 'validar_cpfcnpj input-text');
            }else{
                $j('.inputcnpj').attr('name', 'NULL');
                $j('.inputcpf').attr('name', 'cpfcnpj');
            }

            /*Exibe ou oculta os boxs*/
            $j('.boxpj').hide();
            $j('.boxpf').show();

            /*Exibe ou oculta o entregar em outro endereço conforme a selecao do tipo pessoa*/
            $j('li.options').find("label:contains('Entregar')").css('visibility', 'visible');
            $j('input[name*="[same_as_billing]"]').css('visibility', 'visible');

        }else if(tipovindobanco == 'Juridica'){
          /*juricica*/

            /*Se existe o Taxvat alterna entre eles mudando o name conforme selecionado o tipo pessoa*/
            if( existe != ''){
                $j('input[name*="taxvat-old"]').attr('name', 'taxvat');
                $j('input[name*="taxvat"]:eq(0)').attr('name', 'NULL');

                /*Se existe add a class validar_cpfcnpj*/
                $j('input[name*="taxvat"]').attr('class', 'validar_cpfcnpj input-text');
            }else{
                $j('.inputcnpj').attr('name', 'cpfcnpj');
                $j('.inputcpf').attr('name', 'NULL');
            }

            /*Exibe ou oculta os boxs*/
            $j('.boxpj').show();
            $j('.boxpf').hide();

            /*Exibe ou oculta o entregar em outro endereço conforme a selecao do tipo pessoa*/
            $j('li.options').find("label:contains('Entregar')").css('visibility', 'hidden');
            $j('input[name*="[same_as_billing]"]').css('visibility', 'hidden');
        }

//]]>
</script>
